# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestilling',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Band'),
        ),
        migrations.AlterField(
            model_name='konserter',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Band'),
        ),
    ]
