# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170919_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestilling',
            name='godkjent',
            field=models.NullBooleanField(choices=[(True, 'Godkjent'), (False, 'Ikke godkjent'), (None, 'Ikke vurdert enda')], default=''),
        ),
    ]
