# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170919_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.CharField(blank=True, max_length=255)),
                ('dokument', models.FileField(upload_to='documents/')),
                ('opplastet', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bestilling',
            name='godkjent',
            field=models.NullBooleanField(choices=[(True, 'Godkjent'), (False, 'Ikke godkjent'), (None, 'Ikke vurdert enda')], default=None),
        ),
    ]
