# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170919_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='konserter',
            name='publikumsantall',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bestilling',
            name='godkjent',
            field=models.NullBooleanField(choices=[(True, 'Godkjent'), (False, 'Ikke godkjent'), (None, 'Ikke vurdert enda')], default=None),
        ),
    ]
