# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170928_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konserter',
            name='band',
        ),
        migrations.AddField(
            model_name='konserter',
            name='band',
            field=models.ManyToManyField(blank=True, to='webapp.Band'),
        ),
    ]
