# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170926_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tekniske_behov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.CharField(blank=True, max_length=255)),
                ('dokument', models.FileField(upload_to='documents/')),
                ('opplastet', models.DateTimeField(auto_now_add=True)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Band')),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
