# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170928_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konserter',
            name='publikumsantall',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
