# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170926_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tekniske_behov',
            name='dokument',
        ),
        migrations.AddField(
            model_name='tekniske_behov',
            name='backline',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tekniske_behov',
            name='behov',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
