# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170928_1606'),
        ('webapp', '0005_auto_20171003_1042'),
    ]

    operations = [
    ]
