# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20171003_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestilling',
            name='pris',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
