# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_merge_20171004_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('storrelse', models.IntegerField()),
                ('kostnad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='konserter',
            name='publikumsantall',
            field=models.IntegerField(blank=True, default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='konserter',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Scene'),
        ),
    ]
