# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_merge_20171004_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='albums_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='band',
            name='previous_concerts',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='band',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='konserter',
            name='publikumsantall',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
