# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_merge_20171004_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konserter',
            name='publikumsantall',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
