# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170928_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240)),
                ('value', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Ordbok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Band')),
            ],
        ),
        migrations.RemoveField(
            model_name='tekniske_behov',
            name='beskrivelse',
        ),
        migrations.AddField(
            model_name='keyvaluepair',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Ordbok'),
        ),
    ]
