# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20171017_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scene',
            new_name='Scener',
        ),
    ]
