# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20170928_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backline', models.CharField(db_index=True, max_length=50)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Band')),
            ],
        ),
        migrations.RemoveField(
            model_name='keyvaluepair',
            name='container',
        ),
        migrations.RemoveField(
            model_name='ordbok',
            name='band',
        ),
        migrations.RemoveField(
            model_name='tekniske_behov',
            name='band',
        ),
        migrations.AlterField(
            model_name='tekniske_behov',
            name='backline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Backline'),
        ),
        migrations.DeleteModel(
            name='KeyValuePair',
        ),
        migrations.DeleteModel(
            name='Ordbok',
        ),
    ]
