# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20171003_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tekniske_behov',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Band'),
        ),
    ]
