# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20171017_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scener',
            options={'verbose_name_plural': 'Scener'},
        ),
    ]
