# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20171017_1112'),
        ('webapp', '0008_auto_20171017_1037'),
    ]

    operations = [
    ]
