# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_merge_20171004_1133'),
        ('webapp', '0009_tekniske_behov_band'),
    ]

    operations = [
    ]
