# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20171017_0921'),
        ('webapp', '0010_merge_20171018_2036'),
    ]

    operations = [
    ]
