# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20171017_0959'),
        ('webapp', '0007_auto_20171017_1054'),
        ('webapp', '0011_merge_20171018_2106'),
    ]

    operations = [
    ]
