# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_merge_20171018_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestilling',
            name='pris',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
