# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_merge_20171018_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='konserter',
            name='billetpris',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='konserter',
            name='solgtebilletter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
