# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_bestilling_pris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestilling',
            name='pris',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bestilling',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Scener'),
        ),
    ]
