# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20171019_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konserter',
            old_name='billetpris',
            new_name='billettpris',
        ),
    ]
