# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_bestilling_pris'),
        ('webapp', '0013_auto_20171019_1356'),
    ]

    operations = [
    ]
