# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_merge_20171024_1749'),
        ('webapp', '0014_merge_20171024_1903'),
    ]

    operations = [
    ]
