# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_merge_20171026_1137'),
        ('webapp', '0013_auto_20171024_1955'),
    ]

    operations = [
    ]
