# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20171109_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='kontakt_info',
            field=models.TextField(blank=True),
        ),
    ]
