# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20171031_0917'),
        ('webapp', '0019_auto_20171109_1236'),
    ]

    operations = [
    ]
