# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_merge_20171109_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestilling',
            name='pris',
            field=models.PositiveIntegerField(),
        ),
    ]
